version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: 
      - "15672:15672"    
      - "5672:5672" 
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  redis:
    image: "redis"
    command: redis-server --requirepass 1q2w3e4r
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

  app : 
    build : .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"    
    depends_on:
      - rabbitmq
      - redis
    environment:
      - REDIS_HOST=host.docker.internal

  worker:
    build: .
    user : nobody
    depends_on:
      - rabbitmq
      - redis
      - app
    environment:
      - REDIS_HOST=host.docker.internal  
