version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: 
      - "15672:15672"    
      - "5672:5672" 
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  redis:
    image: redis:latest 
    container_name: redis
    ports:
      - "6379:6379"

  app : 
    build : .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"    
    depends_on:
      - rabbitmq
      - redis

  worker:
    build: ./worker
    user : nobody
    depends_on:
      - rabbitmq
      - redis
      - app

